base_dir: '/home/aryan/ws/Airloc_baseline/AirObject/data_pkl/images_1.pkl'
datasets: ["mp3d"]
method: 'airobj' # ['2d_baseline', '3d_baseline', 'netvlad', 'seqnet', 'airobj', 'seqnet_1', 'airobj_1']# 'airobj_1': AirObject (s_l = 1), 'seqnet_1': SeqNet (s_l = 1)
netvlad_model_path: '../models/netvlad_model.pth'
airloc_model_path: '../models/airloc_model_gat_1.pth'
ref_path: '/home/aryan/ws/Airloc_baseline/AirObject/ref_data/airloc_gat_1.pkl'
batch_size: 16
model:
  airloc:
    descriptor_dim: 8192
    hidden_dim: 4096
    nout: 2048
    graph_model: gat
    points_encoder_dims: [2, 4, 8, 16]
    dropout: 0.8 #0.5
    alpha: 0.2
    nheads: 4 #8
    temporal_encoder_dim: 2048
    temporal_encoder_out_dim: 2048
    temporal_kernel_size: 1
    train:
      seqlen: 4
      batch_size: 16
      positive_margin: 1
      negative_margin: 0.2
      lambda_d: 1
      epochs: 25
      lr: 0.0001
      checkpoint: 500
  netvlad:
    descriptor_dim: 256
    vlad_numc: 32