base_dir: "/home/aryan/Mp3d_dataset/x_view" # YT-VIS Train directory
datasets: ["mp3d"]
log_dir: './experiments/train_airloc' # Logging directory
airobj_model_path: './models/gcn_model.pth' # Path to YT-VIS Finetuned Graph Attention Encoder
netvlad_model_path: '../models/netvlad_model.pth'
resume: False
sum_iter: 
optimizer_path: ''
model:
  airloc:
    descriptor_dim: 8192
    hidden_dim: 4096
    nout: 2048
    points_encoder_dims: [2, 4, 8, 16]
    dropout: 0.5
    alpha: 0.2
    nheads: 8
    temporal_encoder_dim: 2048
    temporal_encoder_out_dim: 2048
    temporal_kernel_size: 1
    train:
      seqlen: 4
      batch_size: 16
      positive_margin: 1
      negative_margin: 0.2
      lambda_d: 1
      epochs: 5
      lr: 0.0001
      checkpoint: 500
  netvlad:
    descriptor_dim: 256
    vlad_numc: 32